name: General task
description: Create a general task or enhancement
title: "[Task] "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What needs to be done and why?
    validations:
      required: true
